%%
% Riccardo Antonello (riccardo.antonello@unipd.it)
%
% June 05, 2026
%
% Dept. of Information Engineering, University of Padova
%

%   select serial port 
%   Note: use serialportlist() to check for available serial ports
serialPortName = "/dev/cu.usbmodem154438801"; 

%   define packet specifier
packetSpec = {'uint32'};

%   select baud rate
%   Note: ignored for Teensy USB serial connection (always communicates at 
%   native USB speed, either 12 or 480 Mbit/sec)
baudRate = 115200;

%   configure scopes
plotsGridSize = [1, 1];
plotsContentList = [1, 1, 1];   %   format: scope id, signal id, component id

%   start serialDataLoggerApp with specified input arguments
serialDataLoggerApp( ... 
    "SerialPortName", serialPortName, ...
    "PacketSpec", packetSpec, ...
    "baudRate", baudRate, ...
    "assertDTR", true, ...
    "enableCOBS", true, ...
    "enableNullTerminator", true, ...
    "bufferSize", 2000, ...
    "txSampleTime", 0.01, ...
    "enableLogToWorkspace", true, ...
    "enableSaveOnExit", true, ...
    "varName", "data", ...
    "plotsGridSize", plotsGridSize, ...
    "plotsContentList", plotsContentList, ...
    "plotsDuration", 5, ...
    "plotsRefreshRatio", 8);


