function makeInfo = rtwmakecfg()

%%
% Riccardo Antonello (riccardo.antonello@unipd.it)
% 
% April 02, 2026
% 
% Dept. of Information Engineering, University of Padova 


%%  Root folders 

%   get full path of current dir
mfilepath = mfilename('fullpath');
[currdir, ~, ~] = fileparts(mfilepath);

%   get Support Packages base dir
baseRoot = matlabshared.supportpkg.getSupportPackageRoot();

%   get Teensyduino base dir
if ispc
    teensyRoot = fullfile(baseRoot, ...
        '3P.instrset', '..', 'aCLI', 'data', ...
        'packages', 'teensy', 'hardware', 'avr', '1.58.2');
else
    teensyRoot = fullfile(baseRoot, ...
        '3P.instrset', 'arduinoide.instrset', 'aCLI', 'data', ...
        'packages', 'teensy', 'hardware', 'avr', '1.58.2');
end

%   get Teensy cores dir
coreRoot = fullfile(teensyRoot, 'cores', 'teensy4');

%   get Teensy libraries dir
libRoot = fullfile(teensyRoot, 'libraries');


%%  Include paths (recursive)  

makeInfo.includePath    =   { ...
    coreRoot, ...
    fullfile(libRoot, 'Wire'), ...
    fullfile(libRoot, 'SPI'), ...
    fullfile(currdir, '..', 'Lib', 'TCA9548'), ...
    fullfile(currdir, '..', 'Lib', 'XENSIV_TLx493D') };


%%  Source paths

makeInfo.sourcePath     =   { ...
    fullfile(coreRoot), ...
    fullfile(libRoot, 'Wire'), ...
    fullfile(libRoot, 'SPI'), ...
    fullfile(currdir, '..', 'Lib', 'TCA9548'), ...
    fullfile(currdir, '..', 'Lib', 'XENSIV_TLx493D') };

makeInfo.sources        =   { ...
    'sfun_MagLevTbx_MagSens_v40_WrappedFcns.cpp', ...
    'Wire.cpp', ...
    'WireIMXRT.cpp', ...
    'SPI.cpp', ...
    'TCA9548.cpp', ...
    'BoardSupportUsingKit2Go.cpp', ...
    'CommunicationInterface.cpp', ...
    'IICUsingTwoWire.cpp', ...
    'Kit2GoBoardSupport.cpp', ...
    'Logger.cpp', ...
    'TLx493D_A1B6.c', ... 
    'TLx493D_A2B6.c', ... 
    'TLx493D_A2BW.c', ...
    'TLx493D_P2B6.c', ...
    'TLx493D_P3B6.c', ...
    'TLx493D_P3I8.c', ...
    'TLx493D_W2B6.c', ...
    'TLx493D_W2BW.c', ...
    'tlx493d_common.c', ...
    'tlx493d_gen_2_common.c', ...
    'tlx493d_gen_3_common.c', ...
    'tlx493d.c' };

makeInfo.linkLibsObjs   =   {};
makeInfo.precompile     =   0;
makeInfo.library        =   {};

end