%%
% Riccardo Antonello (riccardo.antonello@unipd.it)
%
% June 07, 2026
%
% Dept. of Information Engineering, University of Padova
%

%   Either run serialDataLoggerApp() and configure the parameters from GUI,
%   or pass the desired settings from command line as specified below.

%   select serial port 
%   Note: use serialportlist() to check for available serial ports
serialPortName = "/dev/cu.usbmodem163412001"; 

%   define packet specifier
packetSpec = {'single', 'single', 'single', 'single', 'single'};

%   select baud rate
%   Note: ignored for Teensy USB serial connection (always communicates at 
%   native USB speed, either 12 or 480 Mbit/sec)
baudRate = 115200;

%   configure scopes
plotsGridSize = [3, 1];
plotsContentList = [ ...
    1, 1, 1; ...    %   format: scope id, signal id, component id
    1, 2, 1; ...    %
    2, 3, 1; ...    %
    3, 4, 1; ...    %
    3, 5, 1];       %

%   start serialDataLoggerApp with specified input arguments
serialDataLoggerApp( ... 
    "SerialPortName", serialPortName, ...
    "PacketSpec", packetSpec, ...
    "baudRate", baudRate, ...
    "assertDTR", true, ...
    "enableCOBS", true, ...
    "enableNullTerminator", true, ...
    "bufferSize", 2000, ...
    "txSampleTime", datalog.Ts, ...
    "enableLogToWorkspace", true, ...
    "enableSaveOnExit", true, ...
    "varName", "data", ...
    "plotsGridSize", plotsGridSize, ...
    "plotsContentList", plotsContentList, ...
    "plotsDuration", 10, ...
    "plotsRefreshRatio", 4);


